# Site settings
title: Vonfitbjj_
email: vstrickl.git@gmail.com
url: https://podcast.vonfitbjj.com
lead: "A podcast about fitness, nutrition and local news."
description: "Click the link below to listen on your favorite podcast service. Choose Anchor for more distributiion options."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#040737'
  links: '#fff'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Podcasts
podcast:
  - title: link
    url: https://www.vonfitbjj.com/
  - title: spotify
    url: https://open.spotify.com/show/3djBbiTC1zvlElMiIvsj5g
  - title: podcast
    url: https://podcasts.apple.com/us/podcast/dan-vons-podcast/id1621032392
anchor:
  - title: anchor
    url: https://anchor.fm/vonfitbjj_

# Build settings
markdown: kramdown
permalink: pretty
